language: php
dist: trusty
sudo: false

matrix:
  include:
    - php: "5.2"
      dist: precise
      env: PHP52SUCKS=true
    - php: "5.3"
      dist: precise
    - php: "5.4"
    - php: "5.5"
    - php: "5.6"
    - php: "7.0"
    - php: "7.1"
      env: MONKEY_PATCH=true
    - php: "7.2"
      env: MONKEY_PATCH=true
    - php: "7.3"
      env: MONKEY_PATCH=true
    - php: "7.4"
      env: MONKEY_PATCH=true

install:
  - |
    if [[ $PHP52SUCKS == true ]]; then
      wget http://download.pear.php.net/package/HTML_Common2-2.1.2.tgz
      pear install --offline ./HTML_Common2-2.1.2.tgz
    else
      pear channel-update pear.php.net
      composer install --no-dev
    fi
  - |
    # Export Composer's global bin dir to PATH, but not on PHP 5.2 (borrowed from Wordpress):
    if [[ $PHP52SUCKS != true ]]; then
      composer config --list --global
      export COMPOSER_GLOBAL=`composer config --list --global | grep '\[home\]' | { read a; echo "${a#* }"; }`
      export PATH="${COMPOSER_GLOBAL}/vendor/bin:$PATH"
    fi
  - |
    # Global install of a supported PHPUnit version
    if [[ $PHP52SUCKS != true ]]; then
      composer global require "phpunit/phpunit=^3.7|^4.8|^5.7"
    fi
  - |
    # Monkey patch phpunit/phpunit-mock-objects
    if [[ $MONKEY_PATCH == true ]]; then
      cp tests/MockObjectGenerator.patched.php ${COMPOSER_GLOBAL}/vendor/phpunit/phpunit-mock-objects/src/Framework/MockObject/Generator.php
    fi

script:
  - which phpunit
  - phpunit --version
  # Do not test composer installation on PHP 5.2 due to lack of composer
  - if [[ $PHP52SUCKS != true ]]; then phpunit ./tests; fi
  - pear package-validate ./package.xml
  - php ./pear-package-helper.php
  - pear install ./.pear-package/package.xml
  # Run tests on HTML_QuickForm2 installed with pear
  - cd `pear config-get test_dir` && phpunit HTML_QuickForm2
